- id: '1652604926204'
  alias: Away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.away_from_home
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_lights_off
    metadata: {}
  - service: script.indoor_cameras_on
    data: {}
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.thermostat_eco_mode
  mode: single
- id: '1652605093279'
  alias: Coming Home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.home
    metadata: {}
  - service: script.indoor_cameras_off
    data: {}
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.thermostat_eco_mode
  mode: single
- id: '1652605141617'
  alias: Coming Home (Dark)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_lights_on
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.home
    metadata: {}
  - condition: device
    type: is_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  - type: turn_on
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  mode: single
- id: '1652605230748'
  alias: Sunset (at home)
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: numeric_state
    entity_id: zone.home
    above: '0'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_lights_on
    metadata: {}
  mode: single
- id: '1664074895423'
  alias: Morning
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -6
  condition: []
  action:
  - type: turn_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  mode: single
- id: '1671321699663'
  alias: Christmas Lighting
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: template
    value_template: '{{ now().month == 12 }}'
  action:
  - type: turn_on
    device_id: 81b684f54340316ad98fe83ed190ea38
    entity_id: switch.christmas_tree
    domain: switch
  - type: turn_on
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  mode: single
- id: '1673047879540'
  alias: Trash Day
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ now().isoweekday() == 4 }}'
      sequence:
      - service: select.select_option
        data:
          option: Trash Day
        target:
          entity_id: select.trash_day
    default:
    - service: select.select_option
      data:
        option: Not Trash Day
      target:
        entity_id: select.trash_day
  mode: single
- id: '1673503803986'
  alias: Reload Broken Thermostat Entry
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: template
    value_template: |
      {{ as_timedelta(states('sensor.last_thermostat_sensor_update')) > as_timedelta('0:30:00') }}
  action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 4dfd032ff9de3f1d14a4fee8de4a0d43
  mode: single
