- id: '1652604926204'
  alias: Away
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    to: '0'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.away_from_home
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.lights_off
    metadata: {}
  - service: script.indoor_cameras_on
    data: {}
  - service: climate.set_preset_mode
    data:
      preset_mode: Away
    target:
      entity_id: climate.living_room_2
  mode: single
- id: '1652605093279'
  alias: Coming Home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.home
    metadata: {}
  - service: script.indoor_cameras_off
    data: {}
  - service: climate.set_preset_mode
    data:
      preset_mode: Home
    target:
      entity_id: climate.living_room_2
  mode: single
- id: '1652605141617'
  alias: Coming Home (Dark)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
    from: '0'
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 4
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on
    metadata: {}
  - service: scene.turn_on
    target:
      entity_id: scene.home
    metadata: {}
  - condition: device
    type: is_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  - type: turn_on
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  mode: single
- id: '1652605230748'
  alias: Sunset (at home)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: 4
  condition:
  - condition: numeric_state
    entity_id: zone.home
    above: '0'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on
    metadata: {}
  mode: single
- id: '1664074895423'
  alias: Morning
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: -6
  condition: []
  action:
  - type: turn_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  - type: turn_off
    device_id: 81b684f54340316ad98fe83ed190ea38
    entity_id: switch.christmas_tree
    domain: switch
  mode: single
- id: '1671321699663'
  alias: Christmas Lighting
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: template
    value_template: '{{ now().month == 12 }}'
  action:
  - type: turn_on
    device_id: 81b684f54340316ad98fe83ed190ea38
    entity_id: switch.christmas_tree
    domain: switch
  - type: turn_on
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: switch.front_door_lights
    domain: switch
  mode: single
- id: '1673047879540'
  alias: Trash Day
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ now().isoweekday() == 4 }}'
      sequence:
      - service: select.select_option
        data:
          option: Trash Day
        target:
          entity_id: select.trash_day
    default:
    - service: select.select_option
      data:
        option: Not Trash Day
      target:
        entity_id: select.trash_day
  mode: single
- id: '1673503803986'
  alias: Reload Broken Thermostat Entry
  trigger:
  - platform: time_pattern
    minutes: /30
  condition:
  - condition: template
    value_template: '{{ as_timedelta(states(''sensor.last_thermostat_sensor_update''))
      > as_timedelta(''0:30:00'') }}

      '
  action:
  - service: homeassistant.reload_config_entry
    data:
      entry_id: 49992082efd965afbeb5a9e0f18908fa
  mode: single
- id: '1678660146641'
  alias: Sync Kitchen Lights
  description: ''
  use_blueprint:
    path: aderusha/link_multiple_devices.yaml
    input:
      linked_entities:
      - switch.kitchen_lights
      - switch.under_cabinet_lighting
- id: '1694405005569'
  alias: Garage to Front Door Lights
  description: ''
  trigger:
  - platform: device
    device_id: 74b8b249f14ced2439d9d3d7443e7e2f
    domain: cover
    entity_id: 3472cb77b41fcc0da6d28e1eb992e3b1
    type: opening
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  - condition: numeric_state
    entity_id: zone.home
    above: 0
  action:
  - condition: device
    type: is_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: 96ba36b666d7801ae00675a3b683b1be
    domain: switch
  - type: turn_on
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: 96ba36b666d7801ae00675a3b683b1be
    domain: switch
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: c3614de33d75a997cb7c50c933a6f9c6
    entity_id: 96ba36b666d7801ae00675a3b683b1be
    domain: switch
  mode: single
- id: '1700479687297'
  alias: Ecobee Follow Me off for Sleep
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.living_room_2
    attribute: preset_mode
    to: Sleep
  condition: []
  action:
  - service: ecobee.set_occupancy_modes
    data:
      follow_me: false
    target:
      entity_id: climate.living_room_2
  mode: single
- id: '1700479726554'
  alias: Ecobee Follow Me on after Sleep
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.living_room_2
    attribute: preset_mode
    from: Sleep
  condition: []
  action:
  - service: ecobee.set_occupancy_modes
    data:
      follow_me: true
    target:
      entity_id: climate.living_room_2
  mode: single
- id: '1700479838658'
  alias: HVAC off when window opens
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.guest_bathroom_window_contact
    to: 'on'
  condition: []
  action:
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.living_room_2
  mode: single
- id: '1700479885347'
  alias: HVAC on when window closes
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.guest_bathroom_window_contact
    to: 'off'
  condition: []
  action:
  - service: climate.turn_on
    data: {}
    target:
      entity_id: climate.living_room_2
  mode: single
