- platform: smartir
  name: Office AC
  unique_id: office_ac
  device_code: 9999
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.office_remote
  temperature_sensor: sensor.office_remote_temperature
  humidity_sensor: sensor.office_remote_humidity
- platform: smartir
  name: Bedroom AC
  unique_id: bedroom_ac
  device_code: 9999
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.bedroom_remote
  temperature_sensor: sensor.bedroom_remote_temperature
  humidity_sensor: sensor.bedroom_remote_humidity
