- platform: smartir
  name: Office AC
  unique_id: office_ac
  device_code: 9999
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.office_remote
  temperature_sensor: sensor.office_remote_temperature
  humidity_sensor: sensor.office_remote_humidity
- platform: smartir
  name: Bedroom AC
  unique_id: bedroom_ac
  device_code: 9999
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.bedroom_remote
  temperature_sensor: sensor.bedroom_remote_temperature
  humidity_sensor: sensor.bedroom_remote_humidity
- platform: smartir
  name: Downstairs AC
  unique_id: downstairs_ac
  device_code: 9999
  controller_data:
    controller_type: Broadlink
    remote_entity: remote.downstairs_remote
  temperature_sensor: sensor.downstairs_remote_temperature
  humidity_sensor: sensor.downstairs_remote_temperature
- platform: dual_smart_thermostat
  name: Office AC (HA)
  heat_cool_mode: true
  heater: switch.office_heat_toggle
  cooler: switch.office_ac_toggle
  target_sensor: sensor.office_remote_temperature
  humidity_sensor: sensor.office_remote_humidity
  min_temp: 60
  max_temp: 85
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  precision: 0.1
  target_temp_step: 1.0
  # TODO Can this be templated?
  home:
    target_temp_low: 65
    target_temp_high: 85
  away:
    target_temp_low: 60
    target_temp_high: 86 # TODO Expand range (mini-split goes up to 90)
  comfort:
    target_temp_low: 68
    target_temp_high: 80
- platform: dual_smart_thermostat
  name: Bedroom AC (HA)
  heat_cool_mode: true
  heater: switch.bedroom_heat_toggle
  cooler: switch.bedroom_ac_toggle
  target_sensor: sensor.bedroom_remote_temperature
  humidity_sensor: sensor.bedroom_remote_humidity
  min_temp: 60
  max_temp: 85
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  precision: 0.1
  target_temp_step: 1.0
  # TODO Can this be templated?
  home:
    target_temp_low: 65
    target_temp_high: 85
  away:
    target_temp_low: 60
    target_temp_high: 86 # TODO Expand range (mini-split goes up to 90)
  sleep:
    target_temp_low: 66
    target_temp_high: 78
  comfort:
    target_temp_low: 68
    target_temp_high: 80
- platform: dual_smart_thermostat
  name: Downstairs AC (HA)
  heat_cool_mode: true
  heater: switch.downstairs_heat_toggle
  cooler: switch.downstairs_ac_toggle
  target_sensor: sensor.downstairs_remote_temperature
  humidity_sensor: sensor.downstairs_remote_humidity
  min_temp: 60
  max_temp: 85
  cold_tolerance: 1.0
  hot_tolerance: 1.0
  precision: 0.1
  target_temp_step: 1.0
  # TODO Can this be templated?
  home:
    target_temp_low: 65
    target_temp_high: 85
  away:
    target_temp_low: 60
    target_temp_high: 86 # TODO Expand range (mini-split goes up to 90)
  comfort:
    target_temp_low: 68
    target_temp_high: 80
