
# Loads default set of integrations. Do not remove.
default_config:

homeassistant: !include basic_info.yaml

# Text to speech
tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret darksky_key

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
template: !include templates.yaml
