# Loads default set of integrations. Do not remove.
default_config:

homeassistant: !include basic_info.yaml

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /hacsfiles/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/hass-bha-icons/hass-bha-icons.js

http:
  cors_allowed_origins:
    - http://localhost:3000
    - http://10.0.0.6:3000
    - http://10.0.0.106:8124

recorder:
  purge_keep_days: 30

automation: !include automations.yaml
input_text: !include input_texts.yaml
media_player: !include media_players.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
template: !include templates.yaml
generic_hygrostat: !include generic_hygrostat.yaml
climate: !include climate.yaml
