- platform: universal
  name: Google Home Speakers
  children:
    - media_player.everywhere
    - media_player.downstairs
    - media_player.upstairs
    - media_player.kitchen_display
    - media_player.living_room_speaker
    - media_player.hallway_speaker
    - media_player.office_nests_2
    - media_player.bedroom_nest
    - media_player.bathroom_speaker
  device_class: speaker
