- platform: time_date
  display_options:
    - 'time'
    - 'date'
    #- 'date_time'
    #- 'date_time_utc'
    #- 'date_time_iso'
    #- 'time_date'
    #- 'time_utc'
    - 'beat'
- platform: statistics
  name: "24h Upload Avg"
  entity_id: sensor.total_upload
  state_characteristic: mean
  sampling_size: 100000
  max_age: 
    hours: 24
- platform: statistics
  name: "1m Upload Max"
  entity_id: sensor.total_upload
  state_characteristic: value_max
  sampling_size: 10
  max_age:
    minutes: 1
- platform: statistics
  name: "24h Download Avg"
  entity_id: sensor.total_download
  state_characteristic: mean
  sampling_size: 100000
  max_age:
    hours: 24
- platform: statistics
  name: "1m Download Max"
  entity_id: sensor.total_download
  state_characteristic: value_max
  sampling_size: 10
  max_age:
    minutes: 1
- platform: systemmonitor
  resources:
    - type: disk_use_percent
    - type: disk_use
    - type: disk_free
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: ipv6_address
      arg: eth0
    - type: processor_use
    - type: processor_temperature
    - type: last_boot
- platform: unifigateway
  host: 10.0.0.1
  port: 443
  username: !secret unifi_username
  password: !secret unifi_password
  version: UDMP-unifiOS
  monitored_conditions:
    - lan
    - wan
    - www
