- platform: template
  switches:
    garage_cam_recording:
      value_template: >
        {{ is_state('select.garage_cam_recording_mode', 'Always') }}
      icon_template: >
        {% if is_state('select.garage_cam_recording_mode', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.garage_cam_recording_mode
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.garage_cam_recording_mode
        data:
          option: Never
    family_room_cam_recording:
      value_template: >
        {{ is_state('select.family_room_cam_recording_mode', 'Always') }}
      icon_template: >
        {% if is_state('select.family_room_cam_recording_mode', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.family_room_cam_recording_mode
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.family_room_cam_recording_mode
        data:
          option: Never
    bedroom_cam_recording:
      value_template: >
        {{ is_state('select.bedroom_cam_recording_mode', 'Always') }}
      icon_template: >
        {% if is_state('select.bedroom_cam_recording_mode', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.bedroom_cam_recording_mode
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.bedroom_cam_recording_mode
        data:
          option: Never
    kitchen_cam_recording:
      value_template: >
        {{ is_state('select.kitchen_cam_recording_mode', 'Always') }}
      icon_template: >
        {% if is_state('select.kitchen_cam_recording_mode', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.kitchen_cam_recording_mode
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.kitchen_cam_recording_mode
        data:
          option: Never
    litterbox_cam_recording:
      value_template: >
        {{ is_state('select.litterbox_cam_recording_mode', 'Always') }}
      icon_template: >
        {% if is_state('select.litterbox_cam_recording_mode', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.litterbox_cam_recording_mode
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.litterbox_cam_recording_mode
        data:
          option: Never
    living_room_cam_recording:
      value_template: >
        {{ is_state('select.living_room_cam_recording_mode_2', 'Always') }}
      icon_template: >
        {% if is_state('select.living_room_cam_recording_mode_2', 'Always') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.living_room_cam_recording_mode_2
        data:
          option: Always
      turn_off:
        service: select.select_option
        target:
          entity_id: select.living_room_cam_recording_mode_2
        data:
          option: Never
    trash_day:
      friendly_name: Trash Day
      value_template: >
        {{ is_state('select.trash_day', 'Trash Day') }}
      icon_template: mdi:delete
      turn_on:
        service: select.select_option
        target:
          entity_id: select.trash_day
        data:
          option: Trash Day
      turn_off:
        service: select.select_option
        target:
          entity_id: select.trash_day
        data:
          option: Trash Day Cleared
