- platform: template
  switches:
    garage_cam_recording:
      value_template: >
        {{ is_state('select.garage_cam_recording_mode', 'Detections') }}
      icon_template: >
        {% if is_state('select.garage_cam_recording_mode', 'Detections') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.garage_cam_recording_mode
        data:
          option: Detections
      turn_off:
        service: select.select_option
        target:
          entity_id: select.garage_cam_recording_mode
        data:
          option: Never
    family_room_cam_recording:
      value_template: >
        {{ is_state('select.family_room_cam_recording_mode', 'Detections') }}
      icon_template: >
        {% if is_state('select.family_room_cam_recording_mode', 'Detections') %}
          mdi:record-rec
        {% else %}
          mdi:record
        {% endif %}
      turn_on:
        service: select.select_option
        target:
          entity_id: select.family_room_cam_recording_mode
        data:
          option: Detections
      turn_off:
        service: select.select_option
        target:
          entity_id: select.family_room_cam_recording_mode
        data:
          option: Never

